// flow-typed signature: a47d112e5346c0b36febb3e23948542c
// flow-typed version: <<STUB>>/eslint-plugin-react-with-styles_v^2.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'eslint-plugin-react-with-styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'eslint-plugin-react-with-styles' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'eslint-plugin-react-with-styles/lib/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-with-styles/lib/rules/no-unused-styles' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-with-styles/lib/rules/only-spread-css' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-with-styles/tests/index' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-with-styles/tests/lib/rules/no-unused-styles' {
  declare module.exports: any;
}

declare module 'eslint-plugin-react-with-styles/tests/lib/rules/only-spread-css' {
  declare module.exports: any;
}

// Filename aliases
declare module 'eslint-plugin-react-with-styles/lib/index.js' {
  declare module.exports: $Exports<'eslint-plugin-react-with-styles/lib/index'>;
}
declare module 'eslint-plugin-react-with-styles/lib/rules/no-unused-styles.js' {
  declare module.exports: $Exports<'eslint-plugin-react-with-styles/lib/rules/no-unused-styles'>;
}
declare module 'eslint-plugin-react-with-styles/lib/rules/only-spread-css.js' {
  declare module.exports: $Exports<'eslint-plugin-react-with-styles/lib/rules/only-spread-css'>;
}
declare module 'eslint-plugin-react-with-styles/tests/index.js' {
  declare module.exports: $Exports<'eslint-plugin-react-with-styles/tests/index'>;
}
declare module 'eslint-plugin-react-with-styles/tests/lib/rules/no-unused-styles.js' {
  declare module.exports: $Exports<'eslint-plugin-react-with-styles/tests/lib/rules/no-unused-styles'>;
}
declare module 'eslint-plugin-react-with-styles/tests/lib/rules/only-spread-css.js' {
  declare module.exports: $Exports<'eslint-plugin-react-with-styles/tests/lib/rules/only-spread-css'>;
}
