// flow-typed signature: 193b564ec6957440dc0d7ff40b038c50
// flow-typed version: <<STUB>>/hook-std_v^1.1.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'hook-std'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'hook-std' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'hook-std/index' {
  declare module.exports: $Exports<'hook-std'>;
}
declare module 'hook-std/index.js' {
  declare module.exports: $Exports<'hook-std'>;
}
