// flow-typed signature: 2c2f650ef429d53506ba7f972c458a8c
// flow-typed version: <<STUB>>/load-script_v^1.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'load-script'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'load-script' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'load-script/test/hello' {
  declare module.exports: any;
}

declare module 'load-script/test/index' {
  declare module.exports: any;
}

declare module 'load-script/test/throw' {
  declare module.exports: any;
}

// Filename aliases
declare module 'load-script/index' {
  declare module.exports: $Exports<'load-script'>;
}
declare module 'load-script/index.js' {
  declare module.exports: $Exports<'load-script'>;
}
declare module 'load-script/test/hello.js' {
  declare module.exports: $Exports<'load-script/test/hello'>;
}
declare module 'load-script/test/index.js' {
  declare module.exports: $Exports<'load-script/test/index'>;
}
declare module 'load-script/test/throw.js' {
  declare module.exports: $Exports<'load-script/test/throw'>;
}
