// flow-typed signature: 83d2fdff81437c07c2397d64f20b7d7f
// flow-typed version: <<STUB>>/noop3_v^999.999.999/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'noop3'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'noop3' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'noop3/factory' {
  declare module.exports: any;
}

// Filename aliases
declare module 'noop3/factory.js' {
  declare module.exports: $Exports<'noop3/factory'>;
}
declare module 'noop3/index' {
  declare module.exports: $Exports<'noop3'>;
}
declare module 'noop3/index.js' {
  declare module.exports: $Exports<'noop3'>;
}
