/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-with-styles'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-with-styles/lib/ThemedStyleSheet' {
  declare module.exports: any;
}

declare module 'react-with-styles' {
  /*
    P = Props
    OP = OwnProps
    Def = DefaultProps
    St = State
  */

  declare export type StyleDefinition = {
    [key: string]: {
      _name: string,
      _definition: Object,
    },
  };

  declare export function withStyles(
    styles: Object,
  ): <Props, Component: React$ComponentType<Props>>(
    WrappedComponent: Component,
    // return class because of https://github.com/facebook/flow/issues/6057
  ) => Class<React$Component<$Diff<React$ElementConfig<Component>, { styles: any }>>>;

  declare export var css: (...definitions: Array<StyleDefinition | false>) => { className: string };
}
