// flow-typed signature: 89ea2f1b80c9d528c190285c74b3572e
// flow-typed version: <<STUB>>/react-with-styles-interface-aphrodite_v^5.0.0/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-with-styles-interface-aphrodite'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-with-styles-interface-aphrodite' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-with-styles-interface-aphrodite/lib/aphroditeInterface' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/lib/aphroditeInterfaceFactory' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/lib/no-important' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/lib/utils/resolveLTR' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/lib/utils/resolveRTL' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/lib/utils/separateStyles' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/no-important' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/aphroditeInterface' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/aphroditeInterfaceFactory' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/no-important' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/utils/resolveLTR' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/utils/resolveRTL' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/src/utils/separateStyles' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/aphroditeInterface_test' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/aphroditeInterfaceFactory_test' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/no-important_test' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/utils/resolveLTR_test' {
  declare module.exports: any;
}

declare module 'react-with-styles-interface-aphrodite/test/utils/resolveRTL_test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-with-styles-interface-aphrodite/lib/aphroditeInterface.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/aphroditeInterface'>;
}
declare module 'react-with-styles-interface-aphrodite/lib/aphroditeInterfaceFactory.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/aphroditeInterfaceFactory'>;
}
declare module 'react-with-styles-interface-aphrodite/lib/no-important.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/no-important'>;
}
declare module 'react-with-styles-interface-aphrodite/lib/utils/resolveLTR.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/utils/resolveLTR'>;
}
declare module 'react-with-styles-interface-aphrodite/lib/utils/resolveRTL.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/utils/resolveRTL'>;
}
declare module 'react-with-styles-interface-aphrodite/lib/utils/separateStyles.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/lib/utils/separateStyles'>;
}
declare module 'react-with-styles-interface-aphrodite/no-important.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/no-important'>;
}
declare module 'react-with-styles-interface-aphrodite/src/aphroditeInterface.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/aphroditeInterface'>;
}
declare module 'react-with-styles-interface-aphrodite/src/aphroditeInterfaceFactory.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/aphroditeInterfaceFactory'>;
}
declare module 'react-with-styles-interface-aphrodite/src/no-important.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/no-important'>;
}
declare module 'react-with-styles-interface-aphrodite/src/utils/resolveLTR.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/utils/resolveLTR'>;
}
declare module 'react-with-styles-interface-aphrodite/src/utils/resolveRTL.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/utils/resolveRTL'>;
}
declare module 'react-with-styles-interface-aphrodite/src/utils/separateStyles.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/src/utils/separateStyles'>;
}
declare module 'react-with-styles-interface-aphrodite/test/aphroditeInterface_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/aphroditeInterface_test'>;
}
declare module 'react-with-styles-interface-aphrodite/test/aphroditeInterfaceFactory_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/aphroditeInterfaceFactory_test'>;
}
declare module 'react-with-styles-interface-aphrodite/test/no-important_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/no-important_test'>;
}
declare module 'react-with-styles-interface-aphrodite/test/utils/resolveLTR_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/utils/resolveLTR_test'>;
}
declare module 'react-with-styles-interface-aphrodite/test/utils/resolveRTL_test.js' {
  declare module.exports: $Exports<'react-with-styles-interface-aphrodite/test/utils/resolveRTL_test'>;
}
