// flow-typed signature: 200e9ab3ae5c662a816426cb09949564
// flow-typed version: <<STUB>>/reflexbox_v^3.0.1/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'reflexbox'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'reflexbox' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'reflexbox/dist/Box' {
  declare module.exports: any;
}

declare module 'reflexbox/dist/config' {
  declare module.exports: any;
}

declare module 'reflexbox/dist/context-types' {
  declare module.exports: any;
}

declare module 'reflexbox/dist/css' {
  declare module.exports: any;
}

declare module 'reflexbox/dist/Flex' {
  declare module.exports: any;
}

declare module 'reflexbox/dist/index' {
  declare module.exports: any;
}

declare module 'reflexbox/dist/reflex' {
  declare module.exports: any;
}

declare module 'reflexbox/dist/ReflexProvider' {
  declare module.exports: any;
}

declare module 'reflexbox/dist/sheet' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/App' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/Banner' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/Border' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/Btn' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/bundle' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/Button' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/Card' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/colors' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/entry' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/examples/Align' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/examples/Column' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/examples/Directions' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/examples/FlexAuto' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/examples/Grid' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/examples/Hero' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/examples/index' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/examples/MarginAuto' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/examples/Offset' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/examples/Padding' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/examples/Wrap' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/Fill' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/Nav' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/Pre' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/Text' {
  declare module.exports: any;
}

declare module 'reflexbox/docs/updaters' {
  declare module.exports: any;
}

declare module 'reflexbox/src/Box' {
  declare module.exports: any;
}

declare module 'reflexbox/src/config' {
  declare module.exports: any;
}

declare module 'reflexbox/src/context-types' {
  declare module.exports: any;
}

declare module 'reflexbox/src/css' {
  declare module.exports: any;
}

declare module 'reflexbox/src/Flex' {
  declare module.exports: any;
}

declare module 'reflexbox/src/index' {
  declare module.exports: any;
}

declare module 'reflexbox/src/reflex' {
  declare module.exports: any;
}

declare module 'reflexbox/src/ReflexProvider' {
  declare module.exports: any;
}

declare module 'reflexbox/src/sheet' {
  declare module.exports: any;
}

declare module 'reflexbox/test' {
  declare module.exports: any;
}

declare module 'reflexbox/webpack.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'reflexbox/dist/Box.js' {
  declare module.exports: $Exports<'reflexbox/dist/Box'>;
}
declare module 'reflexbox/dist/config.js' {
  declare module.exports: $Exports<'reflexbox/dist/config'>;
}
declare module 'reflexbox/dist/context-types.js' {
  declare module.exports: $Exports<'reflexbox/dist/context-types'>;
}
declare module 'reflexbox/dist/css.js' {
  declare module.exports: $Exports<'reflexbox/dist/css'>;
}
declare module 'reflexbox/dist/Flex.js' {
  declare module.exports: $Exports<'reflexbox/dist/Flex'>;
}
declare module 'reflexbox/dist/index.js' {
  declare module.exports: $Exports<'reflexbox/dist/index'>;
}
declare module 'reflexbox/dist/reflex.js' {
  declare module.exports: $Exports<'reflexbox/dist/reflex'>;
}
declare module 'reflexbox/dist/ReflexProvider.js' {
  declare module.exports: $Exports<'reflexbox/dist/ReflexProvider'>;
}
declare module 'reflexbox/dist/sheet.js' {
  declare module.exports: $Exports<'reflexbox/dist/sheet'>;
}
declare module 'reflexbox/docs/App.js' {
  declare module.exports: $Exports<'reflexbox/docs/App'>;
}
declare module 'reflexbox/docs/Banner.js' {
  declare module.exports: $Exports<'reflexbox/docs/Banner'>;
}
declare module 'reflexbox/docs/Border.js' {
  declare module.exports: $Exports<'reflexbox/docs/Border'>;
}
declare module 'reflexbox/docs/Btn.js' {
  declare module.exports: $Exports<'reflexbox/docs/Btn'>;
}
declare module 'reflexbox/docs/bundle.js' {
  declare module.exports: $Exports<'reflexbox/docs/bundle'>;
}
declare module 'reflexbox/docs/Button.js' {
  declare module.exports: $Exports<'reflexbox/docs/Button'>;
}
declare module 'reflexbox/docs/Card.js' {
  declare module.exports: $Exports<'reflexbox/docs/Card'>;
}
declare module 'reflexbox/docs/colors.js' {
  declare module.exports: $Exports<'reflexbox/docs/colors'>;
}
declare module 'reflexbox/docs/entry.js' {
  declare module.exports: $Exports<'reflexbox/docs/entry'>;
}
declare module 'reflexbox/docs/examples/Align.jsx' {
  declare module.exports: $Exports<'reflexbox/docs/examples/Align'>;
}
declare module 'reflexbox/docs/examples/Column.jsx' {
  declare module.exports: $Exports<'reflexbox/docs/examples/Column'>;
}
declare module 'reflexbox/docs/examples/Directions.jsx' {
  declare module.exports: $Exports<'reflexbox/docs/examples/Directions'>;
}
declare module 'reflexbox/docs/examples/FlexAuto.jsx' {
  declare module.exports: $Exports<'reflexbox/docs/examples/FlexAuto'>;
}
declare module 'reflexbox/docs/examples/Grid.jsx' {
  declare module.exports: $Exports<'reflexbox/docs/examples/Grid'>;
}
declare module 'reflexbox/docs/examples/Hero.jsx' {
  declare module.exports: $Exports<'reflexbox/docs/examples/Hero'>;
}
declare module 'reflexbox/docs/examples/index.js' {
  declare module.exports: $Exports<'reflexbox/docs/examples/index'>;
}
declare module 'reflexbox/docs/examples/MarginAuto.jsx' {
  declare module.exports: $Exports<'reflexbox/docs/examples/MarginAuto'>;
}
declare module 'reflexbox/docs/examples/Offset.jsx' {
  declare module.exports: $Exports<'reflexbox/docs/examples/Offset'>;
}
declare module 'reflexbox/docs/examples/Padding.jsx' {
  declare module.exports: $Exports<'reflexbox/docs/examples/Padding'>;
}
declare module 'reflexbox/docs/examples/Wrap.jsx' {
  declare module.exports: $Exports<'reflexbox/docs/examples/Wrap'>;
}
declare module 'reflexbox/docs/Fill.js' {
  declare module.exports: $Exports<'reflexbox/docs/Fill'>;
}
declare module 'reflexbox/docs/Nav.js' {
  declare module.exports: $Exports<'reflexbox/docs/Nav'>;
}
declare module 'reflexbox/docs/Pre.js' {
  declare module.exports: $Exports<'reflexbox/docs/Pre'>;
}
declare module 'reflexbox/docs/Text.js' {
  declare module.exports: $Exports<'reflexbox/docs/Text'>;
}
declare module 'reflexbox/docs/updaters.js' {
  declare module.exports: $Exports<'reflexbox/docs/updaters'>;
}
declare module 'reflexbox/src/Box.js' {
  declare module.exports: $Exports<'reflexbox/src/Box'>;
}
declare module 'reflexbox/src/config.js' {
  declare module.exports: $Exports<'reflexbox/src/config'>;
}
declare module 'reflexbox/src/context-types.js' {
  declare module.exports: $Exports<'reflexbox/src/context-types'>;
}
declare module 'reflexbox/src/css.js' {
  declare module.exports: $Exports<'reflexbox/src/css'>;
}
declare module 'reflexbox/src/Flex.js' {
  declare module.exports: $Exports<'reflexbox/src/Flex'>;
}
declare module 'reflexbox/src/index.js' {
  declare module.exports: $Exports<'reflexbox/src/index'>;
}
declare module 'reflexbox/src/reflex.js' {
  declare module.exports: $Exports<'reflexbox/src/reflex'>;
}
declare module 'reflexbox/src/ReflexProvider.js' {
  declare module.exports: $Exports<'reflexbox/src/ReflexProvider'>;
}
declare module 'reflexbox/src/sheet.js' {
  declare module.exports: $Exports<'reflexbox/src/sheet'>;
}
declare module 'reflexbox/test.js' {
  declare module.exports: $Exports<'reflexbox/test'>;
}
declare module 'reflexbox/webpack.config.js' {
  declare module.exports: $Exports<'reflexbox/webpack.config'>;
}
