// flow-typed signature: f88f395694dcf147cd4fa2e0aa157b6c
// flow-typed version: <<STUB>>/webpack-stylish_v^0.1.8/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'webpack-stylish'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'webpack-stylish' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'webpack-stylish/lib/parse' {
  declare module.exports: any;
}

declare module 'webpack-stylish/lib/style' {
  declare module.exports: any;
}

// Filename aliases
declare module 'webpack-stylish/index' {
  declare module.exports: $Exports<'webpack-stylish'>;
}
declare module 'webpack-stylish/index.js' {
  declare module.exports: $Exports<'webpack-stylish'>;
}
declare module 'webpack-stylish/lib/parse.js' {
  declare module.exports: $Exports<'webpack-stylish/lib/parse'>;
}
declare module 'webpack-stylish/lib/style.js' {
  declare module.exports: $Exports<'webpack-stylish/lib/style'>;
}
