// flow-typed signature: 76b5276180b5d9e1cf12bf6895e4faac
// flow-typed version: <<STUB>>/z-shop-ui_vhttps://mosaic01.ztat.net/npm/z-shop-ui.tgz/flow_v0.69.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'z-shop-ui'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'z-shop-ui' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'z-shop-ui/dist/icon-meta' {
  declare module.exports: any;
}

declare module 'z-shop-ui/dist/z-shop-ui.development' {
  declare module.exports: any;
}

declare module 'z-shop-ui/dist/z-shop-ui' {
  declare module.exports: any;
}

declare module 'z-shop-ui/dist/z-shop-ui.production' {
  declare module.exports: any;
}

// Filename aliases
declare module 'z-shop-ui/dist/icon-meta.js' {
  declare module.exports: $Exports<'z-shop-ui/dist/icon-meta'>;
}
declare module 'z-shop-ui/dist/z-shop-ui.development.js' {
  declare module.exports: $Exports<'z-shop-ui/dist/z-shop-ui.development'>;
}
declare module 'z-shop-ui/dist/z-shop-ui.js' {
  declare module.exports: $Exports<'z-shop-ui/dist/z-shop-ui'>;
}
declare module 'z-shop-ui/dist/z-shop-ui.production.js' {
  declare module.exports: $Exports<'z-shop-ui/dist/z-shop-ui.production'>;
}
